name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

#    - name: Lint Code Base
#      uses: docker://github/super-linter:latest

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: bash scripts/build.sh

#    - name: Test
#      run: go test -v .
